"""add processing_context table

Revision ID: 8f75caf3f18a
Revises: f9899c7aeb52
Create Date: 2026-09-13 10:21:34.472754

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f75caf3f18a'
down_revision: Union[str, Sequence[str], None] = 'f9899c7aeb52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('processing_context',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('scan_id', sa.String(length=36), nullable=False),
    sa.Column('purpose', sa.Enum('Marketing', 'Analytics', 'CustomerSupport', 'LegalCompliance', 'Other', name='purpose'), nullable=False),
    sa.Column('consent_status', sa.Enum('Available', 'NotAvailable', 'Unknown', name='consentstatus'), nullable=False),
    sa.Column('retention_value', sa.Integer(), nullable=False),
    sa.Column('retention_unit', sa.Enum('days', 'months', 'years', name='retentionunit'), nullable=False),
    sa.Column('access_scope', sa.Text(), nullable=False),
    sa.Column('encryption_enabled', sa.Boolean(), nullable=False),
    sa.Column('access_control_enabled', sa.Boolean(), nullable=False),
    sa.Column('notice_status', sa.Enum('Available', 'Missing', name='noticestatus'), nullable=False),
    sa.Column('submitted_by', sa.String(length=36), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['scan_id'], ['datasets.id'], ),
    sa.ForeignKeyConstraint(['submitted_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_processing_context_scan_id'), 'processing_context', ['scan_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_processing_context_scan_id'), table_name='processing_context')
    op.drop_table('processing_context')
    # ### end Alembic commands ###
