"""add pii_detections table

Revision ID: c5927225190d
Revises: fb4c3a0b90a8
Create Date: 2026-09-13 09:58:24.817936

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5927225190d'
down_revision: Union[str, Sequence[str], None] = 'fb4c3a0b90a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pii_detections',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('scan_id', sa.String(length=36), nullable=False),
    sa.Column('field_name', sa.String(length=255), nullable=False),
    sa.Column('masked_sample', sa.String(length=500), nullable=False),
    sa.Column('detector_type', sa.Enum('regex_email', 'regex_phone', 'regex_aadhaar', 'regex_pan', 'regex_ip', 'spacy_person', 'spacy_location', 'column_heuristic', name='detectortype'), nullable=False),
    sa.Column('confidence', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='confidence'), nullable=False),
    sa.Column('row_ref', sa.Integer(), nullable=True),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['scan_id'], ['datasets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pii_detections_scan_id'), 'pii_detections', ['scan_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pii_detections_scan_id'), table_name='pii_detections')
    op.drop_table('pii_detections')
    # ### end Alembic commands ###
