"""add pii_classifications table

Revision ID: f9899c7aeb52
Revises: c5927225190d
Create Date: 2026-09-13 10:14:23.109909

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9899c7aeb52'
down_revision: Union[str, Sequence[str], None] = 'c5927225190d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pii_classifications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('detection_id', sa.String(length=36), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('subtype', sa.String(length=100), nullable=False),
    sa.Column('confidence', sa.String(length=20), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('classified_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['detection_id'], ['pii_detections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pii_classifications_detection_id'), 'pii_classifications', ['detection_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pii_classifications_detection_id'), table_name='pii_classifications')
    op.drop_table('pii_classifications')
    # ### end Alembic commands ###
